const FETCH_JOBS = 'FECTH_JOBS'
const APPLY_JOBS = 'APPLY_JOBS'
const FETCH_USER = 'FETCH_USER'
const FETCH_LOST = 'FETCH_LOST'
const CHECK_LOGIN = 'CHECK_LOGIN'
const FILTER_TIME = 'FILTER_TIME'
const FILTER_PERSON = 'FILTER_PERSON'
const FILTER_PRICE = 'FILTER_PRICE'

export {
  FETCH_JOBS,
  FETCH_USER,
  APPLY_JOBS,
  FETCH_LOST,
  CHECK_LOGIN,
  FILTER_TIME,
  FILTER_PERSON,
  FILTER_PRICE
}
